# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rbcurse-extras"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rahul Kumar"]
  s.date = "2012-01-05"
  s.description = "Ruby curses/ncurses widgets for easy application development on text terminals, augmenting rbcurse-core"
  s.email = "sentinel1879@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "VERSION",
    "examples/data/list.txt",
    "examples/data/lotr.txt",
    "examples/data/table.txt",
    "examples/data/tasks.txt",
    "examples/data/unix1.txt",
    "examples/inc/qdfilechooser.rb",
    "examples/inc/rfe_renderer.rb",
    "examples/newtabbedwindow.rb",
    "examples/rfe.rb",
    "examples/test2.rb",
    "examples/testeditlist.rb",
    "examples/testtable.rb",
    "examples/testvimsplit.rb",
    "lib/rbcurse/extras/include/celleditor.rb",
    "lib/rbcurse/extras/include/checkboxcellrenderer.rb",
    "lib/rbcurse/extras/include/comboboxcellrenderer.rb",
    "lib/rbcurse/extras/include/defaultlistselectionmodel.rb",
    "lib/rbcurse/extras/include/listkeys.rb",
    "lib/rbcurse/extras/include/listselectable.rb",
    "lib/rbcurse/extras/include/tableextended.rb",
    "lib/rbcurse/extras/widgets/horizlist.rb",
    "lib/rbcurse/extras/widgets/menutree.rb",
    "lib/rbcurse/extras/widgets/multilinelabel.rb",
    "lib/rbcurse/extras/widgets/rcomboedit.rb",
    "lib/rbcurse/extras/widgets/rlink.rb.moved",
    "lib/rbcurse/extras/widgets/rlistbox.rb",
    "lib/rbcurse/extras/widgets/rmenulink.rb.moved",
    "lib/rbcurse/extras/widgets/rmulticontainer.rb",
    "lib/rbcurse/extras/widgets/rmultisplit.rb",
    "lib/rbcurse/extras/widgets/rmultitextview.rb",
    "lib/rbcurse/extras/widgets/rpopupmenu.rb",
    "lib/rbcurse/extras/widgets/rtable.rb",
    "lib/rbcurse/extras/widgets/rvimsplit.rb",
    "lib/rbcurse/extras/widgets/table/tablecellrenderer.rb",
    "lib/rbcurse/extras/widgets/table/tabledatecellrenderer.rb"
  ]
  s.homepage = "https://github.com/rkumar/rbcurse-extras"
  s.require_paths = ["lib"]
  s.rubyforge_project = "rbcurse"
  s.rubygems_version = "1.8.10"
  s.summary = "Ruby Ncurses Toolkit additional widgets"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rbcurse-core>, [">= 0.0.3"])
    else
      s.add_dependency(%q<rbcurse-core>, [">= 0.0.3"])
    end
  else
    s.add_dependency(%q<rbcurse-core>, [">= 0.0.3"])
  end
end

